### ISSUE TITLE
There should be check if permission enabled alert should not be there thats why i can not use this plugin can you update code to check if autostart enable

### ISSUE THREAD

**Issue by raj860444** [saty932/cordova-plugin-autostart-permission#2]
There should be check if permission enabled alert should not be there thats why i can not use this plugin can you update code to check if autostart enable

**Comment by saty932** [comment]
@raj860444 Android does n't allow you to read whether autostart is enabled by user or not. We had same requirement in that case we had one service which starts in the background when the app is killed there I am setting the variable to true whenever service is started in the background otherwise it will be false by default so whenever user open the app we are showing the autostart popup.

**Comment by raj860444** [comment]
which service you have used actually i was tried for background app ionic 3 plugin for geolocation also but that was not working for me.

**Comment by saty932** [comment]
@raj860444 We have our own plugins for geolocation and beacons which we created there we used above mentioned thing.
